### ISSUE TITLE
all pdfs are just 100kb files that are completely white

### ISSUE THREAD

**Issue by buzztiaan** [Yellow-Beak-Computer/ELLO-2M#2]
eh, oops?

**Comment by knivd** [comment]
I just checked all PDFs, and they are fine. Using Adobe Reader and it opens both the schematics and the 3D renders as well.

**Comment by buzztiaan** [comment]
adobe reader isnt free software

**Comment by knivd** [comment]
I believe it is. The schematic files can be open with any PDF reader. I am not sure about the 3D renders though, but they are not critical

**Comment by buzztiaan** [comment]
free software is not defined like you think it is

**Comment by blu** [comment]
Konstantin, some of the PDFs have issues opening in evince (a very popular GNOME-based reader) as well as in the default PDF reader in iOS. The problematic PDFs are:

panel_MX470.pdf
PCB0.pdf
PCB1_MX470.pdf
PCB2.pdf
PCB3a.pdf
PCB3.pdf
PCB4.pdf

And here's what evince reports to stderr when trying to open one of those:

*\* (evince:3753): WARNING **: Unimplemented annotation: POPPLER_ANNOT_3D.  It is a known issue and it might be implemented in the future.

I understand AdobeReader handles those annotations just fine, but could you, please, consider producing a version of the PDFs without those annotations or using a different type of annotation?
