### ISSUE TITLE
Design not made with available FOSS tools

### ISSUE THREAD

**Issue by buzztiaan** [Yellow-Beak-Computer/ELLO-2M#3]
Could you please redo the pcb in kicad? ty

**Comment by knivd** [comment]
I have never used kicad before, so I can't promise that. But will have a look at it to see if the current design can be imported there somehow

**Comment by buzztiaan** [comment]
i would totally love you if you fixed this issue :) 

using non-opensource tools to make opensource designs is just not-done, and i cant clone your project until it does use opensource tools

**Comment by knivd** [comment]
KiCAD proves to be too distant for my old habits, but converting the design to CircuitMaker (which is free) is quite easy. I just tried and it works perfectly fine. It opens the schematic files directly, but doesn't open the PCB files. However I will export them into CM format and will upload the files in the coming days, and the entire ELLO 2M computer will be available through the CircuitMaker community as well.

**Comment by buzztiaan** [comment]
free but not foss ;)

**Comment by buzztiaan** [comment]
please learn KiCAD or stop calling your project OSHW

**Comment by knivd** [comment]
I consider this post quite aggressive. Don't want to learn KiCAD. 
My design is open-source because you can see the source of it, but it is entirely up to you what you can make out of it.

**Comment by buzztiaan** [comment]
i understand your adversion towards actual improvement of your knowledge, but to adhere to being actual OSHW you have no choice.
